### ISSUE TITLE
Missing dependency lodash._reinterpolate

### ISSUE THREAD

**Issue by mgroenhoff** [tracker1/gulp-footer#8]
`template.js` depends on `lodash._reinterpolate` but it is not a dependency (`lodash.template` has it but you can not rely on this).

**Comment by selected-pixel-jameson** [comment]
I'm also seeing this issue when using the gulp-angular-template cache module. 

```Error: Cannot find module 'lodash._reinterpolate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/xxxxx/Documents/xxxx/website/www/user/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/template.js:6:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)```

**Comment by selected-pixel-jameson** [comment]
Submitted a PR for this. https://github.com/tracker1/gulp-footer/pull/9

**Comment by tracker1** [comment]
Sorry, merged PR and pushed/published

**Comment by mgroenhoff** [comment]
Thanks!

**Comment by selected-pixel-jameson** [comment]
@tracker1 I'm not exactly sure how publishing updates works, but it appears as though this update has gotten pushed out to version 1 as well as version 2. The package dependency issue is a problem with version 1 as well.

**Comment by selected-pixel-jameson** [comment]
@tracker1 Any progress on this?

**Comment by mpriya05** [comment]
I am facing the same issue.  we need to push the code to production asap. it was planned for this friday. 

I'm seeing this issue when using the gulp-angular-template cache module.

[19:32:00] Error: Cannot find module 'lodash._reinterpolate'[0m
(../ux/node_modules/gulp-angular-templatecache/node_modules/gulp-footer/template.js:6:21)[0m
